### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by hungtrieu07** [KhanhVNMC/toidongy-post-spam#1]
![image](https://user-images.githubusercontent.com/69461968/184526088-f91c3e59-6aa4-47e1-8406-8efd336c413d.png)
something wrong in here bro, i'm using virtual machine on Azure (Ubuntu 20.04)

**Comment by KhanhVNMC** [comment]
The web server is now no longer taking data request, the program cannot parse success code so it return an Exception,
(nói chung là bọn nó rén sun cu rồi, đóng request PHP rồi nên app không chạy được nữa)

**Comment by KhanhVNMC** [comment]
![image](https://user-images.githubusercontent.com/71543494/184529395-76c7d6ab-482a-4c4c-bac8-1ed4814d65b6.png)
Added handler for this. Updated version will throw a RuntimeException with the correct error
